name: GitHub Snake Game Contributions

on:
  # Schedule the workflow to run multiple times per day to catch all contributions
  schedule:
    - cron: "0 */6 * * *"  # Run every 6 hours



  # Allow manual triggering of the workflow

  workflow_dispatch:



  # Trigger the workflow on pushes to the main branch

  push:

    branches:

      - main



jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Increased timeout for better processing
    concurrency:
      group: snake-animation
      cancel-in-progress: true  # This ensures only one workflow runs at a time



    steps:

      # Step 1: Checkout the repository

      - name: Checkout Repository

        uses: actions/checkout@v3
      # Step 2: Generate the snake animations with improved settings
      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3.2.0
        with:
          # GitHub username to generate the animation for
          github_user_name: ${{ github.repository_owner }}
          
          # Configuration to ensure all commits are captured
          github_api_token: ${{ secrets.GITHUB_TOKEN }}
          
          # Increase contributions captured
          max_contributions_per_day: 24
          
          # Define the output files with optimized configurations for better visualization
          outputs: |
            dist/github-snake.svg?color_snake=green&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353
            dist/github-snake-dark.svg?palette=github-dark&color_snake=blue&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353
            dist/ocean.gif?color_snake=green&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353

        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Step 3: Deploy the generated files to the 'output' branch with improved settings
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true  # This ensures a clean history on the output branch
          commit_message: "Update snake animation with all contributions [skip ci]"
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
